
package samic.serversamic;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SamicServer", targetNamespace = "http://SamicServer/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SamicServer {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns samic.serversamic.Consulta
     */
    @WebMethod(operationName = "BuscaCpfCnpj")
    @WebResult(partName = "return")
    @Action(input = "http://SamicServer/SamicServer/BuscaCpfCnpjRequest", output = "http://SamicServer/SamicServer/BuscaCpfCnpjResponse")
    public Consulta buscaCpfCnpj(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns samic.serversamic.AcoesArray
     */
    @WebMethod(operationName = "Acoes")
    @WebResult(partName = "return")
    @Action(input = "http://SamicServer/SamicServer/AcoesRequest", output = "http://SamicServer/SamicServer/AcoesResponse")
    public AcoesArray acoes(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "Feito")
    @WebResult(partName = "return")
    @Action(input = "http://SamicServer/SamicServer/FeitoRequest", output = "http://SamicServer/SamicServer/FeitoResponse")
    public boolean feito(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "Inclusao")
    @WebResult(partName = "return")
    @Action(input = "http://SamicServer/SamicServer/InclusaoRequest", output = "http://SamicServer/SamicServer/InclusaoResponse")
    public boolean inclusao(
        @WebParam(name = "arg0", partName = "arg0")
        Consulta arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns samic.serversamic.ConsultaArray
     */
    @WebMethod(operationName = "BuscaCpfsCnpjs")
    @WebResult(partName = "return")
    @Action(input = "http://SamicServer/SamicServer/BuscaCpfsCnpjsRequest", output = "http://SamicServer/SamicServer/BuscaCpfsCnpjsResponse")
    public ConsultaArray buscaCpfsCnpjs(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns samic.serversamic.Cep
     */
    @WebMethod(operationName = "BuscaCepCorreios")
    @WebResult(partName = "return")
    @Action(input = "http://SamicServer/SamicServer/BuscaCepCorreiosRequest", output = "http://SamicServer/SamicServer/BuscaCepCorreiosResponse")
    public Cep buscaCepCorreios(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns samic.serversamic.Cnpj
     */
    @WebMethod(operationName = "BuscaCnpjReceita")
    @WebResult(partName = "return")
    @Action(input = "http://SamicServer/SamicServer/BuscaCnpjReceitaRequest", output = "http://SamicServer/SamicServer/BuscaCnpjReceitaResponse")
    public Cnpj buscaCnpjReceita(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns samic.serversamic.Cpf
     */
    @WebMethod(operationName = "BuscaCpfReceita")
    @WebResult(partName = "return")
    @Action(input = "http://SamicServer/SamicServer/BuscaCpfReceitaRequest", output = "http://SamicServer/SamicServer/BuscaCpfReceitaResponse")
    public Cpf buscaCpfReceita(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2);

}
